# Generated by Django 4.1.3 on 2022-11-10 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_rename_subjects_subject'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='finish_time',
        ),
        migrations.AddField(
            model_name='lessons',
            name='duration',
            field=models.IntegerField(default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='group',
            field=models.CharField(default='no namw', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='teacher',
            field=models.CharField(default='no name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessons',
            name='topic',
            field=models.CharField(default='no name', max_length=50),
            preserve_default=False,
        ),
    ]
